refactoring

diff --git a/bin/kubeconfig_load b/bin/kubeconfig_load
--- a/bin/kubeconfig_load
+++ b/bin/kubeconfig_load
@@ -1,3 +1,8 @@
 #!/bin/bash
+if [[ ! -e ~/.kube/config_$1 ]]; then
+	echo "Not found env $1(~/.kube/config_$1)"
+	exit 1
+fi
+
 cat ~/.kube/config_$1 > ~/.kube/config
-kk cluster-info
+kk_info
